routes:
  /about/: about
  /cocopeat/: cocopeat
  /medicinalProducts/: medicinalProducts
collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
